AWSTemplateFormatVersion: 2010-09-09
Description: Pipeline for priodically build base image

Parameters:
  EcrRepoName:
    Description: ECR Repository name for ProjectBaseImage
    Type: String
    Default: "baseimage/seconds"
  ImageTag:
    Description: Image tag for ProjectBaseImage
    Type: String
    Default: tagimage
  Buildspec:
    Description: Image tag for ProjectBaseImage
    Type: String
    Default: buildspec-2st.yaml
  AwsAccountID:
    Description: AWS Account ID
    Type: String
    Default: <Account-ID>
  S3ArtifactStore:
    Description: S3 location to storing artifact
    Type: String
    Default: sorcecode
  PipelineName:
    Description: Name of CodePipline
    Type: String
    Default: BaseImageBuilder
  CodeCommitRepoName:
    Description: Name of CodeCommit repository
    Type: String
    Default: BaseImageBuilder
  CodeBuildProjectName:
    Description: Name of codebuild project
    Type: String
    Default: ProjectBaseImage
  CodePipelineSNSTopicName:
    Description: Name of sns topic
    Type: String
    Default: CodePipelineSNS
  EmailNotification:
    Description: Emails for notification
    Type: String
    Default: focuszaaphoto@gmail.com

Resources:
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    DeletionPolicy: Delete
    Properties:
      Name: !Ref CodeBuildProjectName
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:2.0
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Value: us-east-1
          - Name: AWS_ACCOUNT_ID
            Value: !Ref AwsAccountID
          - Name: IMAGE_REPO_NAME
            Value: !Ref EcrRepoName
          - Name: IMAGE_TAG
            Value: !Ref ImageTag
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Ref Buildspec
  
  CodeBuildRole:
    Type: 'AWS::IAM::Role'
    DeletionPolicy: Delete
    Properties:
      Description: "codebuild service role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 'sts:AssumeRole'
            Principal: {
              Service: ["codebuild.amazonaws.com"]
            }
      Path: "/"
      RoleName: "codebuild-service-role"
      Policies:
        - PolicyName: codebuild-service-role-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: "CloudWatchLogsPolicy"
                Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: 
                  - !Join [ '', [ 'arn:aws:logs:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':log-group:/aws/codebuild/', !Ref CodeBuildProjectName , ':*' ] ]
              - Sid: "CodeCommitPolicy"
                Effect: Allow
                Action:
                  - 'codecommit:GitPull'
                Resource:
                  - !Join [ '', [ 'arn:aws:codecommit:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':', !Ref CodeCommitRepoName ] ]
              - Sid: "S3Policy"
                Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:GetObjectVersion"
                  - "s3:PutObject"
                  - "s3:GetBucketAcl"
                  - "s3:GetBucketLocation"
                Resource:
                  - !Join [ '', [ 'arn:aws:s3:', '::', !Ref S3ArtifactStore ] ]
                  - !Join [ '', [ 'arn:aws:s3:', '::', !Ref S3ArtifactStore, '/', !Ref PipelineName , '/*'] ]
              - Sid: "EcrWriteAccessPolicy"
                Effect: Allow
                Action:
                  - "ecr:GetDownloadUrlForLayer"
                  - "ecr:BatchGetImage"
                  - "ecr:CompleteLayerUpload"
                  - "ecr:UploadLayerPart"
                  - "ecr:InitiateLayerUpload"
                  - "ecr:BatchCheckLayerAvailability"
                  - "ecr:PutImage"
                Resource:
                  - !Join [ '', [ 'arn:aws:ecr:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':repository/', !Ref EcrRepoName ] ]
                  
              - Sid: "EcrReadAccess"
                Effect: Allow
                Action:
                  - "ecr:GetAuthorizationToken"
                Resource: "*"
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    DeletionPolicy: Delete
    Properties: 
      Name: !Ref PipelineName
      ArtifactStore: 
        Type: S3
        Location: !Ref S3ArtifactStore
      RoleArn: !GetAtt CodePipelineRole.Arn
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeCommit
              OutputArtifacts:
                - Name: SourceBaseImage
              Configuration:
                BranchName: main
                RepositoryName: !Ref CodeCommitRepoName
                PollForSourceChanges: false
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: BuildBaseImage
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              RunOrder: 1
              Configuration:
                ProjectName: !Ref CodeBuildProject
              InputArtifacts:
                - Name: SourceBaseImage
  CodePipelineRole:
    Type: 'AWS::IAM::Role'
    DeletionPolicy: Delete
    Properties:
      Description: "CodePipeline service role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 'sts:AssumeRole'
            Principal: {
              Service: ["codepipeline.amazonaws.com"]
            }
      Path: "/"
      RoleName: "code-pipeline-service-role"
      Policies:
        - PolicyName: code-pipeline-service-role-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: "CloudWatchLogsPolicy"
                Effect: Allow
                Action:
                  - "codecommit:CancelUploadArchive"
                  - "codecommit:GetBranch"
                  - "codecommit:GetCommit"
                  - "codecommit:GetRepository"
                  - "codecommit:GetUploadArchiveStatus"
                  - "codecommit:UploadArchive"
                Resource: 
                  - !Join [ '', [ 'arn:aws:codecommit:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':', !Ref CodeCommitRepoName ] ]
              - Sid: "Codestar"
                Effect: Allow
                Action:
                  - "codestar-notifications:CreateNotificationRule"
                  - "codestar-notifications:DescribeNotificationRule"
                  - "codestar-notifications:UpdateNotificationRule"
                  - "codestar-notifications:DeleteNotificationRule"
                  - "codestar-notifications:Subscribe"
                  - "codestar-notifications:Unsubscribe"
                  - "codestar-notifications:ListNotificationRules"
                  - "codestar-notifications:ListTargets"
                  - "codestar-notifications:ListTagsforResource"
                  - "codestar-notifications:ListEventTypes"
                Resource: !GetAtt NotificationCodePipeline.Arn
              - Sid: "CodeBuildPolicy"
                Effect: Allow
                Action:
                  - "codebuild:BatchGetBuilds"
                  - "codebuild:StartBuild"
                  - "codebuild:BatchGetBuildBatches"
                  - "codebuild:StartBuildBatch"
                Resource: 
                  - !GetAtt CodeBuildProject.Arn
              - Sid: "EcrAccessPolicy"
                Effect: Allow
                Action:
                  - "ecr:DescribeImages"
                Resource:
                  - !Join [ '', [ 'arn:aws:ecr:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':repository/', !Ref EcrRepoName ] ]
              - Sid: "S3Policy"
                Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:GetObjectVersion"
                  - "s3:PutObject"
                  - "s3:GetBucketAcl"
                  - "s3:GetBucketLocation"
                Resource:
                  - !Join [ '', [ 'arn:aws:s3:', '::', !Ref S3ArtifactStore ] ]
                  - !Join [ '', [ 'arn:aws:s3:', '::', !Ref S3ArtifactStore, '/', !Ref PipelineName , '/*'] ]
              - Sid: "SnsPolicy"
                Effect: Allow
                Action:
                  - "sns:Publish"
                Resource:
                  !Join [ '', [ 'arn:aws:sns:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':', !Ref CodePipelineSNSTopicName ] ]

  NotificationCodePipeline:
    Type: 'AWS::CodeStarNotifications::NotificationRule'
    DeletionPolicy: Delete
    Properties:
      Name: 'BaseImageBuilder pipeline result notification'
      DetailType: FULL
      Resource:
        !Join [ '', [ 'arn:aws:codepipeline:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':', !Ref PipelineName ] ]
      EventTypeIds: 
          - codepipeline-pipeline-pipeline-execution-failed
          - codepipeline-pipeline-pipeline-execution-succeeded
      Targets: 
          - TargetType: SNS 
            TargetAddress: 
              !Join [ '', [ 'arn:aws:sns:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':', !Ref CodePipelineSNSTopicName ] ]

  CodePipleineSNSPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties: 
      PolicyDocument:
        Version: "2008-10-17"
        Statement:
          - Sid: "CodePiplineNotificationPublish"
            Effect: Allow
            Action:
              - "SNS:Publish"
            Principal: {
              Service: ["codestar-notifications.amazonaws.com"]
            }
            Resource: 
              - !Join [ '', [ 'arn:aws:sns:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':', !Ref CodePipelineSNS ] ]
      Topics: 
        - !Ref CodePipelineSNS
  
  CodePipelineSNS:
    Type: AWS::SNS::Topic
    DeletionPolicy: Delete
    Properties:
      DisplayName: !Ref CodePipelineSNSTopicName
      Subscription:
        - Endpoint: !Ref EmailNotification
          Protocol: "email"
      TopicName: !Ref CodePipelineSNSTopicName
  
  CodeCommitEventRule:
    Type: AWS::Events::Rule
    DeletionPolicy: Delete
    Properties:
      Name: "EventOnCodeCommit"
      Description: "Start trigger when there is a change on main branch"
      EventPattern:
        source:
          - aws.codecommit
        detail-type:
          - 'CodeCommit Repository State Change'
        resources: 
          - !Join [ '', [ 'arn:aws:codecommit:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':', !Ref CodeCommitRepoName ] ]
        detail:
          event:
            - referenceCreated
            - referenceUpdated
          referenceType:
            - branch
          referenceName:
            - main
      Targets:
        -
          Arn: 
            !Join [ '', [ 'arn:aws:codepipeline:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':', !Ref PipelineName ] ]
          RoleArn: !GetAtt CloudWatchEventRole.Arn
          Id: !Ref PipelineName
  
  EventSchedule:
    Type: AWS::Events::Rule
    DeletionPolicy: Delete
    Properties:
      Name: "WeeklyEventSchedule"
      Description: "Build once a week on Monday random time ~ 8-10 AM  "
      ScheduleExpression: "cron(0 1-5 ? * MON *)"
      Targets:
        -
          Arn: 
            !Join [ '', [ 'arn:aws:codepipeline:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':', !Ref PipelineName ] ]
          RoleArn: !GetAtt CloudWatchEventRole.Arn
          Id: !Ref PipelineName
  
  CloudWatchEventRole:
    Type: 'AWS::IAM::Role'
    DeletionPolicy: Delete
    Properties:
      Description: "Cloudwatch event service role for trigger codepipeline "
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 'sts:AssumeRole'
            Principal: {
              Service: ["events.amazonaws.com"]
            }
      Path: "/"
      RoleName: "cloudwatch-event-service-role"
      Policies:
        - PolicyName: cloudwatch-event-role-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Sid: "StartExecuteCodepipeline"
                Action:
                  - 'codepipeline:StartPipelineExecution'
                Resource:
                  !Join [ '', [ 'arn:aws:codepipeline:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':', !Ref PipelineName ] ]
Outputs:
  CodePiplineArn:
    Description: CodePipeline 
    Value: !Sub 'arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:!Ref PipelineName'
  SNSTopicName:
    Description: SNS 
    Value: !GetAtt CodePipelineSNS.TopicName
  CodeStartNotificationRuleArn:
    Description: CodeStar Notification 
    Value: !GetAtt NotificationCodePipeline.Arn
  CodePiplineRoleArn:
    Description: CodePipeline Role
    Value: !GetAtt CodePipelineRole.Arn
  CodeBuildRoleArn:
    Description: CodeBuildRole Role
    Value: !GetAtt CodeBuildRole.Arn
  CloudWatchEventRoleArn:
    Description: CloudWatchEventRole Role
    Value: !GetAtt CloudWatchEventRole.Arn
  CodeBuildProjectArn:
    Description: CodeBuild 
    Value: !GetAtt CodeBuildProject.Arn
