AWSTemplateFormatVersion: 2010-09-09
Description: Pipeline for priodically build base image

Parameters:
  HermesEcrRepoName:
    Description: ECR Repository name for hermes
    Type: String
    Default: "nlp/hermes"
  CaduceusEcrRepoName:
    Description: ECR Repository name for caduceus
    Type: String
    Default: "nlp/caduceus"
  HermesImageTag:
    Description: Image tag for hermes
    Type: String
    Default: tf-cpu-base
  CaduceusImageTag:
    Description: Image tag for caduceus
    Type: String
    Default: python-slim-base
  HermesBuildspec:
    Description: Image tag for caduceus
    Type: String
    Default: hermes.buildspec.yaml
  CaduceusBuildspec:
    Description: Image tag for caduceus
    Type: String
    Default: caduceus.buildspec.yaml
  AwsAccountID:
    Description: AWS Account ID
    Type: String
    Default: 772907539545
  S3ArtifactStore:
    Description: S3 location to storing artifact
    Type: String
    Default: gbt-stf-assetfiles
  PipelineName:
    Description: Name of CodePipline
    Type: String
    Default: BaseImageBuilder
  CodeCommitRepoName:
    Description: Name of CodeCommit repository
    Type: String
    Default: BaseImageBuilder
  BuildProjectName1:
    Description: Name of codebuild project
    Type: String
    Default: HermesBaseImage
  BuildProjectName2:
    Description: Name of codebuild project
    Type: String
    Default: CaduceusBaseImage
  CodePipelineSNSTopicName:
    Description: Name of sns topic
    Type: String
    Default: CodePipelineSNS

Resources: 
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    DeletionPolicy: Delete
    Properties:
      Name: HermesBaseImage
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:2.0
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Value: us-east-1
          - Name: AWS_ACCOUNT_ID
            Value: !Ref AwsAccountID
          - Name: IMAGE_REPO_NAME
            Value: !Ref HermesEcrRepoName
          - Name: IMAGE_TAG
            Value: !Ref HermesImageTag
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Ref HermesBuildspec

  CodeBuildSeconds:
    Type: AWS::CodeBuild::Project
    DeletionPolicy: Delete
    Properties:
      Name: CaduceusBaseImage
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:2.0
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Value: us-east-1
          - Name: AWS_ACCOUNT_ID
            Value: !Ref AwsAccountID
          - Name: IMAGE_REPO_NAME
            Value: !Ref CaduceusEcrRepoName
          - Name: IMAGE_TAG
            Value: !Ref CaduceusImageTag
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Ref CaduceusBuildspec

# https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-codepipeline-pipeline.html
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    DeletionPolicy: Delete
    Properties: 
      Name: !Ref PipelineName
      ArtifactStore: 
        Type: S3
        Location: !Ref S3ArtifactStore
      RoleArn: !GetAtt CodePipelineRole.Arn
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeCommit
              OutputArtifacts:
                - Name: SourceBaseImage
              Configuration:
                BranchName: main
                RepositoryName: !Ref CodeCommitRepoName
                PollForSourceChanges: false
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: BuildBaseImageHermes
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              RunOrder: 1
              Configuration:
                ProjectName: !Ref CodeBuildProject
              InputArtifacts:
                - Name: SourceBaseImage
            - Name: BuildBaseImageCaduceus
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              RunOrder: 1
              Configuration:
                ProjectName: !Ref CodeBuildSeconds
              InputArtifacts:
                - Name: SourceBaseImage

  CodeCommitEventRule:
    Type: AWS::Events::Rule
    DeletionPolicy: Delete
    Properties:
      Name: "EventOnCodeCommit"
      Description: "Start trigger when there is a change on main branch"
      EventPattern:
        source:
          - aws.codecommit
        detail-type:
          - 'CodeCommit Repository State Change'
        resources: 
          - !Join [ '', [ 'arn:aws:codecommit:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':', !Ref CodeCommitRepoName ] ]
        detail:
          event:
            - referenceCreated
            - referenceUpdated
          referenceType:
            - branch
          referenceName:
            - main
      Targets:
        -
          Arn: 
            !Join [ '', [ 'arn:aws:codepipeline:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':', !Ref PipelineName ] ]
          RoleArn: !GetAtt CloudWatchEventRole.Arn
          Id: !Ref PipelineName

  EventSchedule:
    Type: AWS::Events::Rule
    DeletionPolicy: Delete
    Properties:
      Name: "WeeklyEventSchedule"
      Description: "Build once a week on Monday random time ~ 8-10 AM  "
      ScheduleExpression: "cron(0 1-5 ? * MON *)"
      Targets:
        -
          Arn: 
            !Join [ '', [ 'arn:aws:codepipeline:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':', !Ref PipelineName ] ]
          RoleArn: !GetAtt CloudWatchEventRole.Arn
          Id: !Ref PipelineName

  CloudWatchEventRole:
    Type: 'AWS::IAM::Role'
    DeletionPolicy: Delete
    Properties:
      Description: "Cloudwatch event service role for trigger codepipeline "
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 'sts:AssumeRole'
            Principal: {
              Service: ["events.amazonaws.com"]
            }
      Path: "/"
      RoleName: "cloudwatch-event-service-role"
      Policies:
        - PolicyName: cloudwatch-event-role-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Sid: "StartExecuteCodepipeline"
                Action:
                  - 'codepipeline:StartPipelineExecution'
                Resource:
                  !Join [ '', [ 'arn:aws:codepipeline:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':', !Ref PipelineName ] ]
      Tags:
        - Key: "owned"
          Value: "GBT"

  CodeBuildRole:
    Type: 'AWS::IAM::Role'
    DeletionPolicy: Delete
    Properties:
      Description: "codebuild service role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 'sts:AssumeRole'
            Principal: {
              Service: ["codebuild.amazonaws.com"]
            }
      Path: "/"
      RoleName: "codebuild-service-role"
      Policies:
        - PolicyName: codebuild-service-role-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: "CloudWatchLogsPolicy"
                Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: 
                  - !Join [ '', [ 'arn:aws:logs:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':log-group:/aws/codebuild/', !Ref BuildProjectName1 , ':*' ] ]
                  - !Join [ '', [ 'arn:aws:logs:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':log-group:/aws/codebuild/', !Ref BuildProjectName2 , ':*' ] ]
              - Sid: "CodeCommitPolicy"
                Effect: Allow
                Action:
                  - 'codecommit:GitPull'
                Resource:
                  - !Join [ '', [ 'arn:aws:codecommit:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':', !Ref CodeCommitRepoName ] ]
              - Sid: "S3Policy"
                Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:GetObjectVersion"
                  - "s3:PutObject"
                  - "s3:GetBucketAcl"
                  - "s3:GetBucketLocation"
                Resource:
                  - !Join [ '', [ 'arn:aws:s3:', '::', !Ref S3ArtifactStore ] ]
                  - !Join [ '', [ 'arn:aws:s3:', '::', !Ref S3ArtifactStore, '/', !Ref PipelineName , '/*'] ]
              - Sid: "EcrWriteAccessPolicy"
                Effect: Allow
                Action:
                  - "ecr:GetDownloadUrlForLayer"
                  - "ecr:BatchGetImage"
                  - "ecr:CompleteLayerUpload"
                  - "ecr:UploadLayerPart"
                  - "ecr:InitiateLayerUpload"
                  - "ecr:BatchCheckLayerAvailability"
                  - "ecr:PutImage"
                Resource:
                  - !Join [ '', [ 'arn:aws:ecr:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':repository/', !Ref HermesEcrRepoName ] ]
                  - !Join [ '', [ 'arn:aws:ecr:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':repository/', !Ref CaduceusEcrRepoName ] ]
              - Sid: "EcrReadAccess"
                Effect: Allow
                Action:
                  - "ecr:GetAuthorizationToken"
                Resource: "*"
          
      Tags:
        - Key: "owned"
          Value: "GBT"

  CodePipelineRole:
    Type: 'AWS::IAM::Role'
    DeletionPolicy: Delete
    Properties:
      Description: "CodePipeline service role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 'sts:AssumeRole'
            Principal: {
              Service: ["codepipeline.amazonaws.com"]
            }
      Path: "/"
      RoleName: "code-pipeline-service-role"
      Policies:
        - PolicyName: code-pipeline-service-role-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: "CloudWatchLogsPolicy"
                Effect: Allow
                Action:
                  - "codecommit:CancelUploadArchive"
                  - "codecommit:GetBranch"
                  - "codecommit:GetCommit"
                  - "codecommit:GetRepository"
                  - "codecommit:GetUploadArchiveStatus"
                  - "codecommit:UploadArchive"
                Resource: 
                  - !Join [ '', [ 'arn:aws:codecommit:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':', !Ref CodeCommitRepoName ] ]
              - Sid: "Codestar"
                Effect: Allow
                Action:
                  - "codestar-notifications:CreateNotificationRule"
                  - "codestar-notifications:DescribeNotificationRule"
                  - "codestar-notifications:UpdateNotificationRule"
                  - "codestar-notifications:DeleteNotificationRule"
                  - "codestar-notifications:Subscribe"
                  - "codestar-notifications:Unsubscribe"
                  - "codestar-notifications:ListNotificationRules"
                  - "codestar-notifications:ListTargets"
                  - "codestar-notifications:ListTagsforResource"
                  - "codestar-notifications:ListEventTypes"
                Resource: !GetAtt NotificationCodePipeline.Arn
              - Sid: "CodeBuildPolicy"
                Effect: Allow
                Action:
                  - "codebuild:BatchGetBuilds"
                  - "codebuild:StartBuild"
                  - "codebuild:BatchGetBuildBatches"
                  - "codebuild:StartBuildBatch"
                Resource: 
                  - !GetAtt CodeBuildProject.Arn
                  - !GetAtt CodeBuildSeconds.Arn
                  # - !Join [ '', [ 'arn:aws:codebuild:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':project/', !Ref BuildProjectName1 ] ]
                  # - !Join [ '', [ 'arn:aws:codebuild:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':project/', !Ref BuildProjectName2 ] ]
              - Sid: "EcrAccessPolicy"
                Effect: Allow
                Action:
                  - "ecr:DescribeImages"
                Resource:
                  - !Join [ '', [ 'arn:aws:ecr:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':repository/', !Ref HermesEcrRepoName ] ]
                  - !Join [ '', [ 'arn:aws:ecr:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':repository/', !Ref CaduceusEcrRepoName ] ]
              - Sid: "S3Policy"
                Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:GetObjectVersion"
                  - "s3:PutObject"
                  - "s3:GetBucketAcl"
                  - "s3:GetBucketLocation"
                Resource:
                  - !Join [ '', [ 'arn:aws:s3:', '::', !Ref S3ArtifactStore ] ]
                  - !Join [ '', [ 'arn:aws:s3:', '::', !Ref S3ArtifactStore, '/', !Ref PipelineName , '/*'] ]
              - Sid: "SnsPolicy"
                Effect: Allow
                Action:
                  - "sns:Publish"
                Resource:
                  !Join [ '', [ 'arn:aws:sns:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':', !Ref CodePipelineSNSTopicName ] ]
      Tags:
        - Key: "owned"
          Value: "GBT"

  # https://docs.aws.amazon.com/dtconsole/latest/userguide/concepts.html#events-ref-pipeline
  NotificationCodePipeline:
    Type: 'AWS::CodeStarNotifications::NotificationRule'
    DeletionPolicy: Delete
    Properties:
      Name: 'BaseImageBuilder pipeline result notification'
      DetailType: FULL
      Resource:
        !Join [ '', [ 'arn:aws:codepipeline:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':', !Ref PipelineName ] ]
      EventTypeIds: 
          - codepipeline-pipeline-pipeline-execution-failed
          - codepipeline-pipeline-pipeline-execution-succeeded
      Targets: 
          - TargetType: SNS 
            TargetAddress: 
              !Join [ '', [ 'arn:aws:sns:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':', !Ref CodePipelineSNSTopicName ] ]
      Tags: 
            Owned: GBT

  CodePipleineSNSPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties: 
      PolicyDocument:
        Version: "2008-10-17"
        Statement:
          - Sid: "CodePiplineNotificationPublish"
            Effect: Allow
            Action:
              - "SNS:Publish"
            Principal: {
              Service: ["codestar-notifications.amazonaws.com"]
            }
            Resource: 
              - !Join [ '', [ 'arn:aws:sns:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':', !Ref CodePipelineSNS ] ]
      Topics: 
        - !Ref CodePipelineSNS

  CodePipelineSNS:
    Type: AWS::SNS::Topic
    DeletionPolicy: Delete
    Properties:
      DisplayName: !Ref CodePipelineSNSTopicName
      Subscription:
        - Endpoint: nirut.phengjaiwong@amexgbt.com
          Protocol: "email"
      TopicName: !Ref CodePipelineSNSTopicName

Outputs:
  CodePiplineArn:
    Description: CodePipeline 
    Value: !Sub 'arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:!Ref PipelineName'
  SNSTopicName:
    Description: SNS 
    Value: !GetAtt CodePipelineSNS.TopicName
  CodeStartNotificationRuleArn:
    Description: CodeStar Notification 
    Value: !GetAtt NotificationCodePipeline.Arn
  CodePiplineRoleArn:
    Description: CodePipeline Role
    Value: !GetAtt CodePipelineRole.Arn
  CodeBuildRoleArn:
    Description: CodeBuildRole Role
    Value: !GetAtt CodeBuildRole.Arn
  CloudWatchEventRoleArn:
    Description: CloudWatchEventRole Role
    Value: !GetAtt CloudWatchEventRole.Arn
  CodeBuildProjectArn:
    Description: CodeBuild 
    Value: !GetAtt CodeBuildProject.Arn
  CodeBuildSecondsArn:
    Description: CodeBuild 
    Value: !GetAtt CodeBuildProject.Arn